# -*- coding: utf-8 -*-
"""Medical Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zwiHopG6xKMSIb4RTs_p86T5uNczkRO
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("saifulislamsarfaraz/medical-chatbot-dataset")

print("Path to dataset files:", path)

import kagglehub
import pandas as pd
import numpy as np
import string
import os

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

# Download latest version
path = kagglehub.dataset_download("saifulislamsarfaraz/medical-chatbot-dataset")

print("Path to dataset files:", path)

# List files in the downloaded directory
files = os.listdir(path)
print("Files:", files)

# Read the CSV file (adjust filename if necessary after checking 'files')
csv_file = [f for f in files if f.endswith('.csv')][0]
df = pd.read_csv(os.path.join(path, csv_file))

# Display the first few rows
df.head()

import nltk
from nltk.corpus import stopwords

# Download NLTK English stopwords
nltk.download('stopwords')
english_stopwords = set(stopwords.words('english'))

def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    # 1. Normalisation: lowercase & remove punctuation
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))

    # 2. Tokenisation: split text into word tokens
    tokens = word_tokenize(text)

    # Remove English stopwords
    tokens = [w for w in tokens if w not in english_stopwords]

    # 3. Lemmatisation: convert to base forms (e.g., running -> run)
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]

    # Rejoin into a single string
    return " ".join(lemmatized_tokens)

# Test the function
sample_input = "Do I have a yeast infection? My symptoms are getting worse!"
print("Original:", sample_input)
print("Preprocessed:", preprocess_text(sample_input))

# Specify column names based on your dataset
input_col = 'short_question'
output_col = 'short_answer'

# Clean dataset: drop missing values if any
df = df.dropna(subset=[input_col, output_col]).reset_index(drop=True)

# Apply preprocessing to the questions
df['clean_input'] = df[input_col].apply(preprocess_text)

# Initialize and fit TF-IDF Vectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['clean_input'])

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

def get_bot_response(user_query, threshold=0.1):
    # Preprocess user query
    clean_query = preprocess_text(user_query)

    if not clean_query:
        return "Please enter a valid question or describe your symptoms."

    # Transform query to TF-IDF vector
    query_vector = vectorizer.transform([clean_query])

    # Calculate cosine similarity against all dataset questions
    similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()

    # Get highest similarity score and index
    best_match_idx = np.argmax(similarities)
    best_score = similarities[best_match_idx]

    # Fallback if query confidence is too low
    if best_score < threshold:
        return "I'm sorry, I couldn't find relevant medical information for that. Could you rephrase your question?"

    return df.iloc[best_match_idx][output_col]

import streamlit as st

st.title("Medical Chatbot")

# Streamlit handles the chat UI automatically
prompt = st.chat_input("Ask a question...")
if prompt:
    st.chat_message("user").write(prompt)
    response = get_bot_response(prompt)
    st.chat_message("assistant").write(response)

import kagglehub
import pandas as pd
import numpy as np
import string
import os

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# --- App Setup ---
st.set_page_config(page_title="Medical Chatbot", page_icon="🩺")
st.title("🩺 Medical Assistant Chatbot")

# --- NLTK Setup ---
@st.cache_resource
def load_nltk():
    nltk.download('punkt')
    nltk.download('wordnet')
    nltk.download('stopwords')

load_nltk()

lemmatizer = WordNetLemmatizer()
english_stopwords = set(stopwords.words('english'))

def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in english_stopwords]
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return " ".join(lemmatized_tokens)

# --- Load Dataset & Vectorizer ---
@st.cache_data
def load_data():
    path = kagglehub.dataset_download("saifulislamsarfaraz/medical-chatbot-dataset")
    files = os.listdir(path)
    csv_file = [f for f in files if f.endswith('.csv')][0]
    df = pd.read_csv(os.path.join(path, csv_file))
    
    df = df.dropna(subset=['short_question', 'short_answer']).reset_index(drop=True)
    df['clean_input'] = df['short_question'].apply(preprocess_text)
    
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(df['clean_input'])
    
    return df, vectorizer, tfidf_matrix

df, vectorizer, tfidf_matrix = load_data()

# --- Search Engine ---
def get_bot_response(user_query, threshold=0.1):
    clean_query = preprocess_text(user_query)
    if not clean_query:
        return "Please enter a valid question or describe your symptoms."
    
    query_vector = vectorizer.transform([clean_query])
    similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()
    
    best_match_idx = np.argmax(similarities)
    best_score = similarities[best_match_idx]
    
    if best_score < threshold:
        return "I'm sorry, I couldn't find relevant medical information for that. Could you rephrase your question?"
    
    return df.iloc[best_match_idx]['short_answer']

# --- Streamlit Chat UI ---
if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask a medical question..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    response = get_bot_response(prompt)
    st.session_state.messages.append({"role": "assistant", "content": response})
    with st.chat_message("assistant"):
        st.markdown(response)